In [5]:
import numpy as np

## Normalization Problem

In [7]:
X = np.random.random((5,5))
X

array([[0.10238984, 0.84699237, 0.01114922, 0.75171225, 0.6115297 ],
       [0.99204441, 0.85906946, 0.47261342, 0.08908389, 0.79889525],
       [0.86122601, 0.06340421, 0.03943776, 0.78357792, 0.5208009 ],
       [0.42388997, 0.04159288, 0.67359685, 0.6446575 , 0.88323239],
       [0.89838626, 0.93503979, 0.96745623, 0.87112883, 0.44074944]])

In [19]:
norm = (X-np.mean(X))/np.std(X)
np.save("X_normalized", norm)
norm

array([[-1.44093418,  0.78987753, -1.71428892,  0.50442051,  0.08443688],
       [ 1.22445003,  0.82606021, -0.33175301, -1.48079847,  0.64577967],
       [ 0.83252118, -1.55773419, -1.62953711,  0.59988933, -0.18738446],
       [-0.47772734, -1.62308042,  0.27038862,  0.183687  ,  0.89845177],
       [ 0.94385241,  1.05366552,  1.1507844 ,  0.86218978, -0.42721676]])

## Divisible By 3 Problem

In [43]:
a = np.arange(1,101,1)
a.resize(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
asq=np.square(a)
asq

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [49]:
ifthree = asq%3==0
values=asq[ifthree]
np.save("div_by_3", values)
print(values)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
