In [1]:
import numpy as np

## Normalization Problem

In [13]:
X = np.random.random((5,5))
X

array([[0.81037074, 0.67265848, 0.2292822 , 0.42881296, 0.76862384],
       [0.09317684, 0.52375812, 0.38024799, 0.68969141, 0.09979557],
       [0.68649163, 0.20664272, 0.56282174, 0.48308273, 0.69100567],
       [0.8844766 , 0.6812989 , 0.18378334, 0.72081971, 0.82978232],
       [0.00833762, 0.0413885 , 0.77354755, 0.88235537, 0.67902963]])

In [19]:
x = np.mean(X)
x

0.5204512872134682

In [25]:
o = np.std(X)
o

0.2791159789791307

In [37]:
norm = (X-x)/o
np.save("X_normalized", norm)
norm

array([[ 1.03870604,  0.5453188 , -1.04318315, -0.32831632,  0.88913773],
       [-1.53081327,  0.01184753, -0.50231196,  0.60634338, -1.50710009],
       [ 0.5948794 , -1.12429453,  0.15180231, -0.13388183,  0.611052  ],
       [ 1.30420807,  0.57627518, -1.20619373,  0.71786796,  1.10825268],
       [-1.83477015, -1.71635744,  0.90677811,  1.29660827,  0.568145  ]])

## Divisible By 3 Problem

In [43]:
a = np.arange(1,101,1)
a.resize(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
asq=np.square(a)
asq

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [49]:
ifthree = asq%3==0
values=asq[ifthree]
np.save("div_by_3", values)
print(values)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
